version: '2.1'
services:
  statsd:
    image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/dogstatsd
    ports:
      - '8125:8125/udp'
    command: 'agent'

  consul:
    image: consul
    ports:
      - '8500:8500'
    command: ['agent', '-server', '-bootstrap', '-client', '0.0.0.0']

  knobsui:
    image: 528451384384.dkr.ecr.us-west-2.amazonaws.com/knobs-ui:1.8.1
    environment:
      CONSUL_ADDR: consul:8500
      PORT: 8501
    ports:
      - 8501:8501
    depends_on:
      - consul
